### PR TITLE
Drop PHP 8.0 support, update dependencies and code standards

### PR DESCRIPTION
**Pull request by weph**
Hello again,

there are more changes coming up from my side, as I use your lib in one of my tools, so I figured I might as well do some maintenance chores. This PR includes:

- Introduce Rector and update codebase to PHP8 code standards
- Update Psalm to ^5.7 and increase error level (now down to 3)
- Update PHPUnit to ^10.0 and refactor test code to current standards (attributes instead of docblock annotations mainly)

Running Rector as GitHub action would also be a nice addition to your workflows, but I haven't done that (yet).

### CODE REVIEW

**Comment by weph** [comment]
Oh, well. I forgot that PHPUnit 10 requires PHP8.1.
If you were planning on dropping support for PHP8.0 anyway, this would be a good time.
Otherwise, I can also drop the PHPUnit 10 update.

**Comment by stefanzweifel** [comment]
Yeah, let's drop PHP 8.0 support. 
As there probably won't be any new "big" features coming anyway, users don't miss out. And upgrading to PHP 8.1 is anyway encuraged.

Thanks for the PR!

**Comment by weph** [comment]
There you go 😃

**Review by stefanzweifel — APPROVED** [review]

**Comment by stefanzweifel** [comment]
@weph Thanks again for the PR. Tagged a new release: [v1.3.0](https://github.com/stefanzweifel/commonmark-markdown-renderer/releases/tag/v1.3.0)

**Pull request merged**
